export const RESOURCE_GAIN_MODIFIER = 0.1;

// TODO: remove eslint-disable later
// eslint-disable-next-line import/prefer-default-export
export const RESOURCE_CONSTANTS = {
    BASE_FOOD_PRODUCTION: 2 * RESOURCE_GAIN_MODIFIER,
    BASE_PROD: 2 * RESOURCE_GAIN_MODIFIER,
    BASE_POPULATION_FOOD_YIELD: 1 * RESOURCE_GAIN_MODIFIER,
    BASE_POPULATION_PRODUCTION_YIELD: 1 * RESOURCE_GAIN_MODIFIER,
    BASE_POPULATION_SCIENCE_YIELD: 0.5 * RESOURCE_GAIN_MODIFIER,
};
