import "@/app/globals.css";

import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import Providers from "./providers";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="h-full">
            <Providers>
                <body className="flex h-full">
                    <Sidebar />
                    <div className="flex flex-col grow">
                        <Header />
                        <main className="flex flex-col p-4 grow bg-gray-200">
                            {children}
                        </main>
                    </div>
                </body>
            </Providers>
        </html>
    );
}
