import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Grid from '@mui/material/Unstable_Grid2';
import styles from '../../styles/Home.module.scss';
import { useAppSelector, useAppDispatch } from '../redux/hooks';
import {
    selectFood,
    selectPopulation,
    updateResources,
    selectPopulationCost,
    selectFarmers,
    selectPopulationFoodYield,
    selectPopProdYield,
} from '../redux/reducers/resources';
import MainLayout from '../layouts/main';
import { selectHasIntervalStarted, setIntervalStarted } from '../redux/reducers/game';
import PopCard from '../components/PopCard';

const Home: NextPage = () => {
    const food = useAppSelector(selectFood);
    const popFoodYield = useAppSelector(selectPopulationFoodYield);
    const popProdYield = useAppSelector(selectPopProdYield);
    const population = useAppSelector(selectPopulation);
    const populationCost = useAppSelector(selectPopulationCost);
    const farmers = useAppSelector(selectFarmers);
    const hasIntervalStarted = useAppSelector(selectHasIntervalStarted);

    const dispatch = useAppDispatch();

    // TODO: move this upper since won't work unless you start from / page
    useEffect(() => {
        if (hasIntervalStarted) return;

        dispatch(setIntervalStarted());

        setInterval(() => dispatch(updateResources()), 1000);
    }, []);

    return (
        <div className={styles.container}>
            <MainLayout>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Grid container spacing={2}>
                    <Grid xs={2}>
                        <PopCard
                            icon="Pop"
                            cardTitle={`Population (${population})`}
                            foodYield={popFoodYield}
                            prodYield={popProdYield}
                            progressVal={food}
                            progressMax={populationCost}
                            buttonText="TODO"
                        />
                    </Grid>
                    <Grid xs={2}>
                        <PopCard
                            icon="Farmer"
                            cardTitle={`Farmer (${farmers})`}
                            foodYield={3}
                            progressVal={food}
                            progressMax={populationCost}
                            buttonText="Cost: "
                        />
                    </Grid>
                </Grid>
            </MainLayout>
        </div>
    );
};

export default Home;
