import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Avatar } from '@mui/material';
import styles from '../../styles/Home.module.css';
import { useAppSelector, useAppDispatch } from '../redux/hooks';
import {
    increaseFood,
    selectFood,
    increaseScience,
    selectScience,
    increaseProduction,
    selectProduction,
    increasePopulation,
    selectPopulation,
    updateResources,
} from '../redux/reducers/resources';
import MainLayout from '../layouts/main';
import { selectHasIntervalStarted, setIntervalStarted } from '../redux/reducers/game';

const Home: NextPage = () => {
    const food = useAppSelector(selectFood);
    const science = useAppSelector(selectScience);
    const production = useAppSelector(selectProduction);
    const population = useAppSelector(selectPopulation);
    const hasIntervalStarted = useAppSelector(selectHasIntervalStarted);

    const dispatch = useAppDispatch();

    const handlePopBuy = () => {
        if (food >= 10) {
            dispatch(increasePopulation(1));
        }
    };

    useEffect(() => {
        if (hasIntervalStarted) return;

        dispatch(setIntervalStarted());

        setInterval(() => dispatch(updateResources()), 1000);
    }, []);

    return (
        <div className={styles.container}>
            <MainLayout>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <div>{food.toFixed(1)}</div>
                <Avatar
                    onClick={() => dispatch(increaseFood(1))}
                    sx={{
                        width: '100px',
                        height: '100px',
                        cursor: 'pointer',
                    }}
                    alt="Food clicker"
                    src="/Apple.svg"
                />
                <div>{population}</div>
                <Avatar
                    onClick={handlePopBuy}
                    sx={{
                        width: '100px',
                        height: '100px',
                        cursor: 'pointer',
                    }}
                    alt="Pop clicker"
                    src="/Pop.svg"
                />
                <div>{production.toFixed(1)}</div>
                <Avatar
                    onClick={() => dispatch(increaseProduction(1))}
                    sx={{
                        width: '100px',
                        height: '100px',
                        cursor: 'pointer',
                    }}
                    alt="Production clicker"
                    src="/Production.svg"
                />
                {science > 1 && (
                    <>
                        <div>{science.toFixed(1)}</div>
                        <Avatar
                            onClick={() => dispatch(increaseScience(1))}
                            sx={{
                                width: '100px',
                                height: '100px',
                                cursor: 'pointer',
                            }}
                            alt="Science clicker"
                            src="/science.svg"
                        />
                    </>
                )}
            </MainLayout>
        </div>
    );
};

export default Home;
