import React, { useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Grid from '@mui/material/Unstable_Grid2';
import styles from '../../styles/Home.module.scss';
import { useAppSelector, useAppDispatch } from '../redux/hooks';
import {
    selectFood,
    selectPopulation,
    updateResources,
    selectPopulationCost,
    selectFarmers,
    selectPopulationFoodYield,
    selectPopProdYield,
    increaseFarmers,
    increaseMiners,
    selectHousing,
    selectMiners,
    selectScientists,
} from '../redux/reducers/resources';
import MainLayout from '../layouts/main';
import { selectHasIntervalStarted, setIntervalStarted } from '../redux/reducers/game';
import PopCard from '../components/PopCard';
import { selectBuildings } from '../redux/reducers/buildings';

const Home: NextPage = () => {
    const food = useAppSelector(selectFood);
    const popFoodYield = useAppSelector(selectPopulationFoodYield);
    const popProdYield = useAppSelector(selectPopProdYield);
    const population = useAppSelector(selectPopulation);
    const populationCost = useAppSelector(selectPopulationCost);
    const farmers = useAppSelector(selectFarmers);
    const miners = useAppSelector(selectMiners);
    const scientists = useAppSelector(selectScientists);
    const hasIntervalStarted = useAppSelector(selectHasIntervalStarted);
    const housing = useAppSelector(selectHousing);
    const { Farm, Mine } = useAppSelector(selectBuildings);

    const dispatch = useAppDispatch();

    // TODO: move this upper since won't work unless you start from / page
    useEffect(() => {
        if (hasIntervalStarted) return;

        dispatch(setIntervalStarted());

        setInterval(() => dispatch(updateResources()), 1000);
    }, []);

    return (
        <div className={styles.container}>
            <MainLayout>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Grid container spacing={2}>
                    <Grid xs={6} lg={4} xl={2}>
                        <PopCard
                            icon="Pop"
                            cardTitle={`Population (${population})`}
                            foodYield={popFoodYield}
                            prodYield={popProdYield}
                            progressVal={food}
                            progressMax={populationCost}
                            buttonText="TODO"
                            onButtonClick={() => console.log('haha')}
                        />
                    </Grid>
                    <Grid xs={6} lg={4} xl={2}>
                        <PopCard
                            icon="Farmer"
                            cardTitle={`Farmer (${farmers})`}
                            foodYield={3}
                            buttonText="Buy"
                            hasTextField
                            onButtonClick={(value: number) => dispatch(increaseFarmers(value))}
                            max={Math.min(population, Farm ? Farm.built - farmers : 0)}
                        />
                    </Grid>
                    <Grid xs={6} lg={4} xl={2}>
                        <PopCard
                            icon="Miner"
                            cardTitle={`Miner (${miners})`}
                            prodYield={3}
                            buttonText="Buy"
                            hasTextField
                            onButtonClick={(value: number) => dispatch(increaseMiners(value))}
                            max={Math.min(population, Mine ? Mine.built - miners : 0)}
                        />
                    </Grid>
                    <Grid xs={6} lg={4} xl={2}>
                        <PopCard
                            icon="Scientist"
                            cardTitle={`Scientist (${scientists})`}
                            prodYield={3}
                            buttonText="Buy"
                            hasTextField
                            onButtonClick={(value: number) => dispatch(increaseMiners(value))}
                            max={Math.min(population, Mine ? Mine.built - miners : 0)}
                        />
                    </Grid>
                </Grid>
                <div>{housing}</div>
            </MainLayout>
        </div>
    );
};

export default Home;
